# Generated by Django 5.1 on 2024-09-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_customuser_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
