# Generated by Django 5.1 on 2024-09-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='apellido',
            new_name='last_name',
        ),
    ]
