# Generated by Django 5.1 on 2024-09-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_rename_nombre_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='perfil_empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.perfilempresa'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='perfil_usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.perfilusuario'),
        ),
    ]
