# Generated by Django 5.1 on 2024-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_alter_perfil_descripcion_alter_perfil_localidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_images/'),
        ),
    ]
