# Generated by Django 5.1 on 2024-10-15 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='quotes.favorito'),
        ),
    ]
